name: Functional Tests
on: [pull_request]
jobs:
  simpletest:
    name: Run Simpletest
    runs-on: ubuntu-20.04
    steps:

      - name: Install MariaDB
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: 'mariadb-10.5'
          root-password: 'root'
          auto-start: true

      - name: Verify setup and create database
        run: |
          echo -e '[client]\nuser = root\npassword = root\nhost = 127.0.0.1' > ~/.my.cnf
          mysql -e 'SELECT version()\G'
          mysql -e 'CREATE DATABASE backdrop;'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none

      - name: Checkout Backdrop core
        uses: actions/checkout@v3
        with:
          repository: backdrop/backdrop

      - name: Checkout module
        uses: actions/checkout@v3
        with:
          path: modules/matomo

      - name: Setup Apache
        run: |
          sudo cp -f modules/matomo/.github/workflows/apache/default.conf /etc/apache2/sites-available/000-default.conf
          sudo apt-get install libapache2-mod-fcgid
          sudo a2enmod rewrite proxy fcgid proxy_fcgi
          sudo systemctl start apache2.service
          sudo sed -i -e 's/user = www-data/user = runner/' /etc/php/7.4/fpm/pool.d/www.conf
          sudo sed -i -e 's/listen.owner = www-data/listen.owner = runner/' /etc/php/7.4/fpm/pool.d/www.conf
          sudo systemctl restart php7.4-fpm.service

      - name: Install Backdrop
        run: core/scripts/install.sh --db-url=mysql://root:root@127.0.0.1/backdrop

      - name: Run functional tests
        run: core/scripts/run-tests.sh --force --directory=modules/matomo --verbose --color --concurrency=2 --cache 2>&1
